apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "omar-ui.labels" . | nindent 4 }}
  name: {{ include "omar-ui.fullname" . }}
spec:
  selector:
    {{- include "omar-ui.selectorLabels" . | nindent 4 }}
  ports:
  - name: {{ .Values.internalPort }}-tcp
    port: {{ .Values.externalPort }}
    protocol: TCP
    targetPort: {{ .Values.internalPort }}
  sessionAffinity: None
  type: ClusterIP
