apiVersion: v1
kind: Service
metadata:
  labels: {}
  name: {{ .Values.fullnameOverride }}-app
spec:
  selector:
    app: {{ .Values.fullnameOverride }}
  ports:
  - name: {{ .Values.internalPort }}-tcp
    port: {{ .Values.externalPort }}
    protocol: TCP
    targetPort: {{ .Values.internalPort }}
  sessionAffinity: None
  type: ClusterIP
